; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PyBSAw"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "nControl, LLC"
#define MyAppURL "http://www.ncontrolsec.com/"
#define MyAppExeName "GetWindowsVersion.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7E473DDA-0559-4623-87DD-854E902FA044}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=admin
OutputDir=C:\Temp
OutputBaseFilename=pybsaw_setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Registry]
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{app}\nmap\nmap.exe"
                                                                         
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\*"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\nmap\*"; DestDir: "{app}\nmap"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tcl\*"; DestDir: "{app}\tcl"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tcl\encoding\*"; DestDir: "{app}\tcl\encoding\"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tcl\http1.0\*"; DestDir: "{app}\tcl\http1.0\"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tcl\msgs\*"; DestDir: "{app}\tcl\msgs"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tcl\opt0.4\*"; DestDir: "{app}\tcl\opt0.4"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tcl\tzdata\*"; DestDir: "{app}\tcl\tzdata"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tcl\tzdata\US\*"; DestDir: "{app}\tcl\tzdata\US"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tcl\tzdata\America\*"; DestDir: "{app}\tcl\tzdata\America"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tk\*"; DestDir: "{app}\tk"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tk\images\*"; DestDir: "{app}\tk\images"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tk\msgs\*"; DestDir: "{app}\tk\msgs"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\tk\ttk\*"; DestDir: "{app}\tk\ttk"; Flags: ignoreversion
Source: "C:\Users\smarkey\PycharmProjects\PyBSA\dist\GetWindowsVersion\certifi\*"; DestDir: "{app}\certifi"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

